### ISSUE TITLE
Completion for routing not working

### ISSUE THREAD

**Issue by maartenba** [Haehnchen/idea-php-drupal-symfony2-bridge#2]
Completion for routing is not working in Drupal 8.

Steps to reproduce:

* Open any Drupal 8 module and enable Symfony2 plugin and this bridge plugin
* Find any usage of ```\Drupal::url()``` and invoke completion
* See no suggestions are shown, while this would be expected:

![drupal_symfony_bridge_6](https://cloud.githubusercontent.com/assets/485230/4489432/eb9ce22c-4a1a-11e4-907a-6232e3e63a56.png)

* Related "go to declaration" also does not seem to be available where this would be expected:

![drupal_symfony_bridge_7](https://cloud.githubusercontent.com/assets/485230/4489510/0c1f72f2-4a1c-11e4-8e20-06750f9e3a9d.png)

* **Note**: in twig templates, this actually does work and completion is provided in calls like ```{{ url('....') }}```

Haven't found anything of interest in the idea.log file. If there is a way of enabling additional logging I'd bemore than happy to do so.

(note screenshots were taken with an older PhpStorm 8 EAP where this did work)

**Comment by Haehnchen** [comment]
should be fix already; but also added this method to route generator list.
