### ISSUE TITLE
Installation doesn't complete for Drupal 8 on MacOSX

### ISSUE THREAD

**Issue by eridu-origin** [Haehnchen/idea-php-drupal-symfony2-bridge#28]
PHPStorm tech support has verified that installation works using a XAMPP localhost, but on MacOSX Sierra (trying to install Drupal 8) the installation messages in the console do not appear for Drupal-specific file types or adding any libraries/includes. This is true for both MAMP Pro and Bitnami Stack localhost server setups.
[idea-log.txt](https://github.com/Haehnchen/idea-php-drupal-symfony2-bridge/files/966301/idea-log.txt)

**Comment by Haehnchen** [comment]
you are wrong here. This Plugin does not provide the Drupal Core functionality. You should report to JetBrains
