### ISSUE TITLE
Drupal 8 File Types not in Use for Code Complete

### ISSUE THREAD

**Issue by eridu-origin** [Haehnchen/idea-php-drupal-symfony2-bridge#30]
According to the documentation at https://confluence.jetbrains.com/display/PhpStorm/Drupal+Development+using+PhpStorm, "Support for Drupal Hooks is provided in .module files only". This would mean that both code complete and Quick Documentation will not work for D8.

In Drupal 8 .module files are hardly used anymore, mainly just for providing online "Help". Custom code will be in .php files, especially Controllers, and maybe in Service container routines. 

The most useful and relevant demonstration would be to enable the Examples for Developers module (https://www.drupal.org/project/examples) and show code completion working with both PHP code and Twig templates.

**Comment by Haehnchen** [comment]
you are wrong here. This Plugin does not provide the Drupal Core functionality. You should report to JetBrains
