### ISSUE TITLE
Drupal Coding Standard "Fix" Link never presented

### ISSUE THREAD

**Issue by eridu-origin** [Haehnchen/idea-php-drupal-symfony2-bridge#31]
The documentation at https://confluence.jetbrains.com/display/PhpStorm/Drupal+Development+using+PhpStorm#DrupalDevelopmentusingPhpStorm-DevelopmentEnvironmentConfiguration

says:

"you will automatically be offered to set Drupal Coding Standard if Drupal integration is enabled. "

But the "Fix this" link is never offered.

**Comment by Haehnchen** [comment]
you are wrong here. This Plugin does not provide the Drupal Core functionality. You should report to JetBrains
