### ISSUE TITLE
Feature Request for Directory Designation

### ISSUE THREAD

**Issue by eridu-origin** [Haehnchen/idea-php-drupal-symfony2-bridge#34]
Please consider documenting the designation of directories for a Drupal 8 PHPStorm project (resource Root, Test, etc).

![directories](https://cloud.githubusercontent.com/assets/342988/25558618/a921f632-2ce7-11e7-8050-0231660bc4c2.png)

If it is part of the installation process it would still be very useful to understand what the logic is behind the designations.

**Comment by Haehnchen** [comment]
you are wrong here. This Plugin does not provide the Drupal Core functionality. You should report to JetBrains
