### ISSUE TITLE
Use of removed RouteParameterReference class in PhpRouteReferenceContributor

### ISSUE THREAD

**Issue by anotherjames** [Haehnchen/idea-php-drupal-symfony2-bridge#52]
In https://github.com/Haehnchen/idea-php-symfony2-plugin/pull/2171, the RouteParameterReference class was removed, but it's still used in PhpRouteReferenceContributor, so this exception occurs:

```
java.lang.NoClassDefFoundError: fr/adrienbrault/idea/symfony2plugin/routing/RouteParameterReference
	at de.espend.idea.php.drupal.references.PhpRouteReferenceContributor$3.getReferencesByElement(PhpRouteReferenceContributor.java:113)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.getReferences(ReferenceProvidersRegistryImpl.java:182)
	at com.intellij.psi.impl.source.resolve.reference.ReferenceProvidersRegistryImpl.mapNotEmptyReferencesFromProviders(ReferenceProvidersRegistryImpl.java:163)
...
```

If I make changes to PHP code in project files, the syntax highlighting just doesn't update - I presume because of this, though I can't be sure.

**Comment by johnzzon** [comment]
Same issue for me. Seems to break inspections as well, because they seem to persist even if there's no issue any more.

**Comment by anotherjames** [comment]
I did find that I could resolve the issue by uninstalling the Symfony Support plugin, and then downloading [this specific older version](https://plugins.jetbrains.com/plugin/7219-symfony-support/versions/stable/337613) which worked (because it still contained the class that _this_ plugin refers to). You can then install it from disk. But then of course phpstorm wants to update the plugin, so you have to remember _not_ to update it until there's a fix here.

**Comment by Haehnchen** [comment]
new drupal plugin just shipped, its now working again.

**Comment by anotherjames** [comment]
Thank you!

**Comment by claudiu-cristea** [comment]
Great 👏
